//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class recoleccion
    {
        public int id { get; set; }
        public Nullable<int> recolector_id { get; set; }
        public Nullable<int> admin_id { get; set; }
        public Nullable<System.DateTime> dia { get; set; }
        public string kilos { get; set; }
        public Nullable<decimal> precio_por_kilo { get; set; }
        public Nullable<decimal> salario_calculado { get; set; }
    
        public virtual admin admin { get; set; }
        public virtual recolector recolector { get; set; }
    }
}
