//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diagram
{
    using System;
    using System.Collections.Generic;
    
    public partial class servicio_recolector
    {
        public int id { get; set; }
        public Nullable<int> servicio_id { get; set; }
        public Nullable<int> recolector_id { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual recolector recolector { get; set; }
        public virtual servicio servicio { get; set; }
    }
}
